# Project information
site_name: Documentation
site_url: https://docs.bnbchain.org
site_author: BNB Chain
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable for all devices
# Repository
repo_name: BNB Chain GitHub
repo_url: https://github.com/huihzhao/docsite
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/bnb.svg
  custom_dir: overrides
  language: en
  icon:
    repo: fontawesome/brands/github
    share: octicons/share-android-24
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode
  features:
#    - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
#    - navigation.instant.progress
    - navigation.tracking
    - navigation.integration
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
#    - navigation.expand
    - navigation.prune
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.action.edit
    - content.tooltips
#    - content.action.view


# Page tree
nav:
  - Home: index.md
  - Announcements:
    - Overview: ./announce/index.md
    - v.9.5.18: ./announce/v.9.5.18.md
  - BNB Chain Fusion:
    - BNB Chain Fusion: ./bc_fusion/index.md
    - Overview: ./bc_fusion/overview.md
    - For Users:
      - Manage Your Assets: ./bc_fusion/users/assets.md
      - Manage Your Atomic Swaps: ./bc_fusion/users/swaps.md
      - Manage Your TimeLocks: ./bc_fusion/users/timelocks.md
      - Manage Your Old Delegations: ./bc_fusion/users/stake-migration.md
      - BEP153 and LSD Stake Migration: ./bc_fusion/users/bep153-stake-migration.md
      - Manage Your New Delegations: ./bc_fusion/users/new-stake.md
      - Participate in Governance: ./bc_fusion/users/gov.md
    - For Token Issuers:
      - Bind Your Tokens: ./bc_fusion/owners/bind.md
    - For Validators:
      - Create New Validators: ./bc_fusion/validators/creation.md
      - Migrate Your Validators: ./bc_fusion/validators/migrations.md
      - Key Management: ./bc_fusion/validators/key-management.md
    - For Developers:
      - New Staking: ./bc_fusion/developers/staking.md
      - New Governance: ./bc_fusion/developers/gov.md
      - Cross Chain Redelegation: ./bc_fusion/developers/crosschain-redelegation.md
      - Build-in System Contracts: ./bc_fusion/developers/system-contracts.md
    - Native Staking & Governance:
      - Staking: ./bc_fusion/validators/staking.md
      - Slash: ./bc_fusion/validators/slash.md
      - Governance: ./bc_fusion/validators/gov.md
  - BNB Smart Chain:
    - BNB Smart Chain: ./bnb_smart_chain/index.md
    - Overview: ./bnb_smart_chain/overview.md
    - Staking:
        - Overview: ./bnb_smart_chain/staking/index.md
        - User Guide: ./bnb_smart_chain/staking/user-guide.md
        - Build Staking dApps: ./bnb_smart_chain/staking/developer-guide.md
    - Governance:
        - Overview: ./bnb_smart_chain/governance/index.md
        - User Guide: ./bnb_smart_chain/governance/user-guide.md
        - Governance APIs: ./bnb_smart_chain/governance/apis.md
    - Validator:
        - Overview: ./bnb_smart_chain/validator/index.md
        - Run Validator: ./bnb_smart_chain/validator/run-val.md
        - Create Validator: ./bnb_smart_chain/validator/create-val.md
        - Secure Validator: ./bnb_smart_chain/validator/security.md
        - Key Management: ./bnb_smart_chain/validator/manage-keys.md
        - MEV:
            - Overview: ./bnb_smart_chain/validator/mev/index.md
            - Validator Guide: ./bnb_smart_chain/validator/mev/validator-integration.md
            - Builder Guide: ./bnb_smart_chain/validator/mev/builder-integration.md
            - FAQs: ./bnb_smart_chain/validator/mev/faqs.md
    - Slashing:
        - Overview: ./bnb_smart_chain/slashing/index.md
        - Slash Rules: ./bnb_smart_chain/slashing/slash-rules.md
        - Slash Monitor: ./bnb_smart_chain/slashing/monitor.md
  - BNB opBNB:
    - BNB opBNB: ./bnb_opbnb/index.md
    - Overview: ./bnb_opbnb/overview.md
    - Core Concepts:
      - Why BSC Requires opBNB: ./bnb_opbnb/core-concepts/why-bsc-requires-opbnb.md
      - Why OP Stack: ./bnb_opbnb/core-concepts/why-opstack.md
      - Optimizations on OP Stack: ./bnb_opbnb/core-concepts/optimisations-on-opstack.md
      - Metrics: ./bnb_opbnb/core-concepts/opbnb-metrics.md
      - Protocol Addresses: ./bnb_opbnb/core-concepts/opbnb-protocol-addresses.md
      - BNBChain Rollup as Service: ./bnb_opbnb/core-concepts/raas.md
    - Get Started:
      - Network Information: ./bnb_opbnb/get-started/network-info.md
      - Wallet Configuration: ./bnb_opbnb/get-started/wallet-configuration.md
      - Deposit to opBNB: ./bnb_opbnb/get-started/deposit-to-opbnb.md
      - Withdraw from opBNB: ./bnb_opbnb/get-started/withdraw-from-opbnb.md
    - Developers:
      - Developer Tools: ./bnb_opbnb/developers/developer-tools.md
      - Network Faucet: ./bnb_opbnb/developers/network-faucet.md
      - Wallet Gas Price Setting: ./bnb_opbnb/developers/set-gas-price.md
      - Multi-sig Wallet: ./bnb_opbnb/developers/multisig-wallet.md
      - BEP20 CrossChain Introduction: ./bnb_opbnb/developers/bep20-crosschain.md
      - Geth P2P Sync Feature: ./bnb_opbnb/developers/geth-sync.md
      - Developers Cheat Sheet: ./bnb_opbnb/developers/cheat-sheet.md
    - Advanced Topics:
      - Local Development: ./bnb_opbnb/advanced/local-dev-env.md
      - Build a Full Stack dApp on opBNB: ./bnb_opbnb/advanced/full-stack-dapp.md
      - Verify Smart Contract on opBNBScan explorer: ./bnb_opbnb/advanced/verify-on-opbnbscan.md
      - Node Best Practices: ./bnb_opbnb/advanced/node-best-practices.md
      - Local Node: ./bnb_opbnb/advanced/local-node.md
      - Run with PebbleDB and PBSS: ./bnb_opbnb/advanced/run-with-pebbledb-and-pbss.md
  - BNB Greenfield:
      - Overview : ./bnb_greenfield/index.md
      - Introduction: ./bnb_greenfield/introduction.md
      - Getting Started:
          - Wallet Configuration: ./bnb_greenfield/getting-started/wallet-configuration.md
          - Bridge and Transfer BNB: ./bnb_greenfield/getting-started/token-transfer.md
          - Use Greenfield in Dcellar: ./bnb_greenfield/getting-started/dcellar.md
          - Greenfield Command: ./bnb_greenfield/getting-started/greenfield-command.md
          - Faucet: ./bnb_greenfield/getting-started/get-test-bnb.md
          - General FAQ: ./bnb_greenfield/getting-started/general-faqs.md
      - Core Concepts:
          - Accounts & Keys: ./bnb_greenfield/core-concept/accounts.md
          - BNB Token Model: ./bnb_greenfield/core-concept/bnb-token-model.md
          - Billing and Payment: ./bnb_greenfield/core-concept/billing-payment.md
          - Data Storage:
              - Simple Storage Service: ./bnb_greenfield/core-concept/data-storage/simple-storage-service.md
              - Underlying Storage Model: ./bnb_greenfield/core-concept/data-storage/data-storage.md
              - Data Integrity and Availability: ./bnb_greenfield/core-concept/data-storage/data-availability.md
          - Cross-Chain Programmability:
              - Cross-Chain Programmability: ./bnb_greenfield/core-concept/cross-chain/programmability.md
              - Resource Mirroring: ./bnb_greenfield/core-concept/cross-chain/mirror.md
              - Smart Contract SDK: ./bnb_greenfield/core-concept/cross-chain/sdk.md
              - Primitive Interfaces: ./bnb_greenfield/core-concept/cross-chain/interface.md
      - For Developers:
          - Quick Guide: ./bnb_greenfield/for-developers/get-started-dev.md
          - Network & Endpoint:
              - Network Info: ./bnb_greenfield/for-developers/network-endpoint/network-info.md
              - RPC Endpoints: ./bnb_greenfield/for-developers/network-endpoint/endpoints.md
              - Contract Entrypoint: ./bnb_greenfield/for-developers/network-endpoint/contract-list.md
          - Bundle Service: ./bnb_greenfield/for-developers/bundle-service.md
          - Tutorials:
              - Overview: ./bnb_greenfield/for-developers/tutorials/overview.md
              - Basic File Management with CLI: ./bnb_greenfield/for-developers/tutorials/file-management-overview.md
              - How to transition from S3 to Greenfield: ./bnb_greenfield/for-developers/tutorials/transitioning-from-s3-to-greenfield.md
              - Hosting a Website on Greenfield: ./bnb_greenfield/for-developers/tutorials/hosting-websites-overview.md
              - Access Control:
                  - Access Control Management with CLI: ./bnb_greenfield/for-developers/tutorials/access-control/cmd-access-control.md
                  - Cross Chain Access Control by CMD: ./bnb_greenfield/for-developers/tutorials/access-control/cross-chain-access-control-by-cmd.md
                  - Native Access Control: ./bnb_greenfield/for-developers/tutorials/access-control/access-control.md
                  - Cross Chain Access Control by SDK: ./bnb_greenfield/for-developers/tutorials/access-control/cross-chain-access-control-by-sdk.md
              - Cross Chain Integration:
                  - Resources Mirroring with CLI: ./bnb_greenfield/for-developers/tutorials/cross-chain-integration/mirror.md
                  - Integrating BSC Smart Contracts with Greenfield Projects: ./bnb_greenfield/for-developers/tutorials/cross-chain-integration/dapp-integration.md
                  - Mirroring FAQ: ./bnb_greenfield/for-developers/tutorials/cross-chain-integration/mirroring-faqs.md
              - Sample Apps on Greenfield:
                  - Overview: ./bnb_greenfield/for-developers/tutorials/app/overview.md
                  - Data Marketplace: ./bnb_greenfield/for-developers/tutorials/app/data-marketplace.md
                  - File Management:
                      - Simple Tool for File Management: ./bnb_greenfield/for-developers/tutorials/app/file-management/basic-file-management.md
                      - Simple Tool for File Management (JS): ./bnb_greenfield/for-developers/tutorials/app/file-management/js-file-managemet.md
                      - Dataset Batch operations: ./bnb_greenfield/for-developers/tutorials/app/file-management/batch-upload.md
                      - Resumable Upload/Download Demo: ./bnb_greenfield/for-developers/tutorials/app/file-management/resumable-upload/overview.md

          - SDKs:
              - Overview: ./bnb_greenfield/for-developers/sdks/index.md
              - Go SDK Example: ./bnb_greenfield/for-developers/sdks/sdk-go.md
              - Javascript SDK Example: ./bnb_greenfield/for-developers/sdks/sdk-js.md
              - Go SDK Official Doc: https://pkg.go.dev/github.com/bnb-chain/greenfield-go-sdk
              - JS SDK Official Doc: https://docs.bnbchain.org/greenfield-js-sdk/
          - How to Contribute: ./bnb_greenfield/for-developers/contribute.md


      - Greenfield Blockchain:
          - Overview: ./bnb_greenfield/greenfield-blockchain/overview.md
          - Blockchain Command Line:  ./bnb_greenfield/greenfield-blockchain/gnfd-cli.md
          - Blockchain Events: ./bnb_greenfield/greenfield-blockchain/events.md
          - Interact with the Chain : ./bnb_greenfield/greenfield-blockchain/interact-node.md
          - Run Greenfield Blockchain:
              - Run Node : ./bnb_greenfield/greenfield-blockchain/run-node/run-node.md
              - Run Relayer : ./bnb_greenfield/greenfield-blockchain/run-node/run-relayer.md
              - Run Challenger : ./bnb_greenfield/greenfield-blockchain/run-node/run-challenger.md
              - Become Validator : ./bnb_greenfield/greenfield-blockchain/run-node/become-validator.md

      - Storage Provider:
          - Overview: ./bnb_greenfield/storage-provider/overview.md
          - Storage Provider Lifecycle: ./bnb_greenfield/storage-provider/storage-provider-lifecycle.md
          - SP Command Line: ./bnb_greenfield/storage-provider/sp-cli.md
          - SP Workflow: ./bnb_greenfield/storage-provider/workflow.md
          - Data Service Quality Standard : ./bnb_greenfield/storage-provider/standard.md
          - Run Storage Provider:
              - SP Compiling and Dependencies: ./bnb_greenfield/storage-provider/run-book/compile-dependences.md
              - Run Local SP Network: ./bnb_greenfield/storage-provider/run-book/run-local-SP-network.md
              - Run SP Node: ./bnb_greenfield/storage-provider/run-book/run-SP-node.md
              - Join SP Network: ./bnb_greenfield/storage-provider/run-book/join-SP-network.md
              - Exit SP Network: ./bnb_greenfield/storage-provider/run-book/exit-SP-network.md
              - Deploy Piece Store: ./bnb_greenfield/storage-provider/run-book/piece-store.md
              - SP Config: ./bnb_greenfield/storage-provider/run-book/config.md
              - SP Common Issues: ./bnb_greenfield/storage-provider/run-book/common-issues.md
              - SP FAQ: ./bnb_greenfield/storage-provider/run-book/sp-faqs.md


      - Releases:
          - Release Notes: ./bnb_greenfield/release-notes/releaseNotes.md
          - Roadmap: ./bnb_greenfield/release-notes/roadmap.md
          - Feature Lists: ./bnb_greenfield/release-notes/features.md
      - Whitepaper: https://github.com/bnb-chain/greenfield-whitepaper

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Link to this section
      toc_depth: 4
  - codehilite
  - admonition
  - footnotes
  - def_list
  - attr_list
  - abbr
  - meta
  - smarty
  - md_in_html
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.extra

plugins:
  - offline
  - search

extra_css:
  - https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap
  - assets/style/index.css
  - assets/style/components/banner.css
  - assets/style/components/nav.css
  - assets/style/components/sidebar.css
  - assets/style/components/content.css
  - assets/style/components/footer-nav.css
  - assets/style/components/footer.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - assets/js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra:
  generator: false
  homepage: https://www.bnbchain.org
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
